# Generated by Django 6.0.2 on 2026-02-23 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableitem',
            options={'ordering': ['-date'], 'verbose_name': 'Элемент таблицы', 'verbose_name_plural': 'Элементы таблицы'},
        ),
        migrations.RemoveField(
            model_name='tableitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tableitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tableitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tableitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tableitem',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 2, 23, 18, 2, 23, 576061, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tableitem',
            name='distance',
            field=models.FloatField(default=0.0, verbose_name='Расстояние'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tableitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
